### ISSUE TITLE
Add GitHub action to notify Slack on star of repo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/linkerd-service-mesh-workshop#14]
**Description:**
When someone stars this repo, it is encouraging to the community of contributors when a notification is received in the community slack workspace.

**Implementation:**
Using this [slack.yaml](https://github.com/layer5io/service-mesh-performance/blob/master/.github/workflows/slack.yml) (GitHub Action) as an example to copy directly from, create a `.github/workflows` folders, copy and modify the slack.yaml file to suite this repo.

**Comment by davidlutta** [comment]
I'd like to work on this kindly assign me.
