### ISSUE TITLE
Add Standard Layer5 GitHub Issue Templates

### ISSUE THREAD

**Issue by leecalcote** [layer5io/linkerd-service-mesh-workshop#15]
**Description:**
Layer5 GitHub repos all have similar GitHub issue templates to assist in providing contributors and users common formats for creating and working with issues.

**Implementation**
Copy the l[ayer5io/meshery repository's issue templates](https://github.com/layer5io/meshery/tree/master/.github/ISSUE_TEMPLATE) into this repo

**Comment by tripathyprateek** [comment]
@leecalcote can I take this up?
